using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class ClientDataSyncModel
{
    [RealtimeProperty(1, true, true)] private string _clientData;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class ClientDataSyncModel : RealtimeModel {
    public string clientData {
        get {
            return _clientDataProperty.value;
        }
        set {
            if (_clientDataProperty.value == value) return;
            _clientDataProperty.value = value;
            InvalidateReliableLength();
            FireClientDataDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(ClientDataSyncModel model, T value);
    public event PropertyChangedHandler<string> clientDataDidChange;
    
    public enum PropertyID : uint {
        ClientData = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _clientDataProperty;
    
    #endregion
    
    public ClientDataSyncModel() : base(null) {
        _clientDataProperty = new ReliableProperty<string>(1, _clientData);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _clientDataProperty.UnsubscribeCallback();
    }
    
    private void FireClientDataDidChange(string value) {
        try {
            clientDataDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _clientDataProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _clientDataProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.ClientData: {
                    changed = _clientDataProperty.Read(stream, context);
                    if (changed) FireClientDataDidChange(clientData);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _clientData = clientData;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
