using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class HandRaiseSyncModel
{
    [RealtimeProperty(1, true, true)] private bool _handRaiseBool;

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class HandRaiseSyncModel : RealtimeModel {
    public bool handRaiseBool {
        get {
            return _handRaiseBoolProperty.value;
        }
        set {
            if (_handRaiseBoolProperty.value == value) return;
            _handRaiseBoolProperty.value = value;
            InvalidateReliableLength();
            FireHandRaiseBoolDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(HandRaiseSyncModel model, T value);
    public event PropertyChangedHandler<bool> handRaiseBoolDidChange;
    
    public enum PropertyID : uint {
        HandRaiseBool = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _handRaiseBoolProperty;
    
    #endregion
    
    public HandRaiseSyncModel() : base(null) {
        _handRaiseBoolProperty = new ReliableProperty<bool>(1, _handRaiseBool);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _handRaiseBoolProperty.UnsubscribeCallback();
    }
    
    private void FireHandRaiseBoolDidChange(bool value) {
        try {
            handRaiseBoolDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _handRaiseBoolProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _handRaiseBoolProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.HandRaiseBool: {
                    changed = _handRaiseBoolProperty.Read(stream, context);
                    if (changed) FireHandRaiseBoolDidChange(handRaiseBool);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _handRaiseBool = handRaiseBool;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
