using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class MuteClientIdSyncModel
{
    [RealtimeProperty(1, true, true)] private int _muteClientId;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class MuteClientIdSyncModel : RealtimeModel {
    public int muteClientId {
        get {
            return _muteClientIdProperty.value;
        }
        set {
            if (_muteClientIdProperty.value == value) return;
            _muteClientIdProperty.value = value;
            InvalidateReliableLength();
            FireMuteClientIdDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(MuteClientIdSyncModel model, T value);
    public event PropertyChangedHandler<int> muteClientIdDidChange;
    
    public enum PropertyID : uint {
        MuteClientId = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _muteClientIdProperty;
    
    #endregion
    
    public MuteClientIdSyncModel() : base(null) {
        _muteClientIdProperty = new ReliableProperty<int>(1, _muteClientId);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _muteClientIdProperty.UnsubscribeCallback();
    }
    
    private void FireMuteClientIdDidChange(int value) {
        try {
            muteClientIdDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _muteClientIdProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _muteClientIdProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.MuteClientId: {
                    changed = _muteClientIdProperty.Read(stream, context);
                    if (changed) FireMuteClientIdDidChange(muteClientId);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _muteClientId = muteClientId;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
